// en_US lang variables

tinymce.addI18n('en_US', {
  "imgmap.title" : 'Image Map Editor',
  "imgmap.desc" : 'Image Map Editor',
  "imgmap.btnUpdate" : 'Update',
  "imgmap.btnCancel" : 'Cancel',
  "imgmap.btnRemove" : 'Remove map',
  "imgmap.add_new_area" : 'Add new area',
  "imgmap.delete_area" : 'Remove area',
  "imgmap.get_image_map": "Get image map HTML",
  "imgmap.img_map_areas" : 'Definitions',
  "imgmap.img_map_zoom" : 'Zoom',
  "imgmap.img_bounding_box" : 'Bounding',
  "imgmap.img_bounding_no_label" : 'without label',
  "imgmap.img_bounding_label_with_number" : 'with numbers',
  "imgmap.img_bounding_label_with_href" : 'with hyperlinks',
  "imgmap.img_bounding_label_with_coords" : 'with coordinates',
  "imgmap.img_image" : 'Bild',
  "imgmap.img_status" : 'Aktions Status',
  "imgmap.FRM_CONTAINER_INFOBASE" : 'Select record',
  "imgmap.FRM_CONTAINER_COORD" : 'Coordinates',
  "imgmap.FRM_CONTAINER_HREF" : 'Link',
  "imgmap.FRM_CONTAINER_TARGET" : 'Target',
  "imgmap.FRM_CONTAINER_TRGT_NEW" : 'New window',
  "imgmap.FRM_CONTAINER_TRGT_THIS" : 'This window',
  "imgmap.FRM_CONTAINER_TRGT_TOP" : 'This page',
  "imgmap.FRM_CONTAINER_TYP_RECT" : 'Rectangle',
  "imgmap.FRM_CONTAINER_TYP_CIRC" : 'Circle',
  "imgmap.FRM_CONTAINER_TYP_POLY" : 'Polygon',
  "imgmap.READY" : 'Ready',
  "imgmap.PREVIEW_MODE" : 'Preview mode. Test your image map.',
  "imgmap.DESIGN_MODE" : 'Design mode. Add new shapes or modify existing ones.',
  "imgmap.HINT_ADD" : 'Add new area',
  "imgmap.HINT_DELETE" : 'Delete selected area',
  "imgmap.HINT_PREVIEW" : 'Preview image map',
  "imgmap.HINT_HTML" : 'Get image map HTML',
  "imgmap.HINT_CLIPBOARD" : 'Copy to clipboard',
  "imgmap.RECTANGLE_DRAW" : 'Drawing rectangle. Hold down SHIFT for square mode.',
  "imgmap.RECTANGLE_MOVE" : 'Moving rectangle',
  "imgmap.RECTANGLE_RESIZE_TOP" : 'Resizing rectangle',
  "imgmap.RECTANGLE_RESIZE_RIGHT" : 'Resizing rectangle',
  "imgmap.RECTANGLE_RESIZE_BOTTOM" : 'Resizing rectangle',
  "imgmap.RECTANGLE_RESIZE_LEFT" : 'Resizing rectangle',
  "imgmap.SQUARE_DRAW" : 'Drawing circle',
  "imgmap.SQUARE2_DRAW" : 'Drawing square. Release SHIFT for rectangle mode.',
  "imgmap.SQUARE_MOVE" : 'Moving circle',
  "imgmap.SQUARE_RESIZE_TOP" : 'Resizing circle',
  "imgmap.SQUARE_RESIZE_RIGHT" : 'Resizing circle',
  "imgmap.SQUARE_RESIZE_BOTTOM" : 'Resizing circle',
  "imgmap.SQUARE_RESIZE_LEFT" : 'Resizing circle',
  "imgmap.POLYGON_DRAW" : 'Drawing polygon. Use SHIFT + click for the last control point.',
  "imgmap.POLYGON_MOVE" : 'Moving polygon',
  "imgmap.ERR_EXCANVAS_LOAD" : 'Excanvas not loaded properly. Try to refresh the page.',
  "imgmap.ERR_INVALID_COORDS" : 'Invalid coordinates.'  
});
