// FR lang variables

tinymce.addI18n('fr_FR', {
  "imgmap.title" : 'Image Map Editor',
  "imgmap.desc" : 'Image Map Editor',
  "imgmap.btnUpdate" : 'Mettre à jour',
  "imgmap.btnCancel" : 'Abandonner',
  "imgmap.btnRemove" : 'Supprimer la map',
  "imgmap.add_new_area" : 'Add new area',
  "imgmap.delete_area" : 'Remove area',
  "imgmap.get_image_map": "Get image map HTML",
  "imgmap.img_map_areas" : 'Definitions',
  "imgmap.img_map_zoom" : 'Zoom',
  "imgmap.img_bounding_box" : 'Bounding',
  "imgmap.img_bounding_no_label" : 'without label',
  "imgmap.img_bounding_label_with_number" : 'with numbers',
  "imgmap.img_bounding_label_with_href" : 'with hyperlinks',
  "imgmap.img_bounding_label_with_coords" : 'with coordinates',
  "imgmap.img_image" : 'Bild',
  "imgmap.img_status" : 'Aktions Status',
  "imgmap.FRM_CONTAINER_INFOBASE" : 'Select record',
  "imgmap.FRM_CONTAINER_COORD" : 'Coordinates',
  "imgmap.FRM_CONTAINER_HREF" : 'Link',
  "imgmap.FRM_CONTAINER_TARGET" : 'Target',
  "imgmap.FRM_CONTAINER_TRGT_NEW" : 'New window',
  "imgmap.FRM_CONTAINER_TRGT_THIS" : 'This window',
  "imgmap.FRM_CONTAINER_TRGT_TOP" : 'This page',
  "imgmap.FRM_CONTAINER_TYP_RECT" : 'Rectangle',
  "imgmap.FRM_CONTAINER_TYP_CIRC" : 'Circle',
  "imgmap.FRM_CONTAINER_TYP_POLY" : 'Polygon',
  "imgmap.READY" : "Pret",
  "imgmap.PREVIEW_MODE" : "Mode pre-visualisation. Test de l'image",
  "imgmap.DESIGN_MODE" : "Mode design. Ajou de nouvelles formes ou modification des existantes",
  "imgmap.HINT_ADD" : "Ajouter une nouvelle zone",
  "imgmap.HINT_DELETE" : "Detruire la zone selectionnee",
  "imgmap.HINT_PREVIEW" : "Pre-visualiser l'image",
  "imgmap.HINT_HTML" : "Obtenir l'image HTML",
  "imgmap.HINT_CLIPBOARD" : "Copier dans le presse papier",
  "imgmap.RECTANGLE_DRAW" : "Dessiner un rectangle. Maintenir enfoncer la touche SHIFT pour le mode carre",
  "imgmap.RECTANGLE_MOVE" : "Deplacer le rectangle",
  "imgmap.RECTANGLE_RESIZE_TOP" : "Redimensionner le rectangle",
  "imgmap.RECTANGLE_RESIZE_RIGHT" : "Redimensionner le rectangle",
  "imgmap.RECTANGLE_RESIZE_BOTTOM" : "Redimensionner le rectangle",
  "imgmap.RECTANGLE_RESIZE_LEFT" : "Redimensionner le rectangle",
  "imgmap.SQUARE_DRAW" : "Dessiner un cercle",
  "imgmap.SQUARE2_DRAW" : "Dessiner un carre. Relacher la touche SHIFT pour le mode rectangle",
  "imgmap.SQUARE_MOVE" : "Deplacer le carre",
  "imgmap.SQUARE_RESIZE_TOP" : "Redimensionner le carre",
  "imgmap.SQUARE_RESIZE_RIGHT" : "Redimensionner le carre",
  "imgmap.SQUARE_RESIZE_BOTTOM" : "Redimensionner le carre",
  "imgmap.SQUARE_RESIZE_LEFT" : "Redimensionner le carre",
  "imgmap.POLYGON_DRAW" : "Dessiner un polygone. Utiliser SHIFT + Click pour le dernier point de controle",
  "imgmap.POLYGON_MOVE" : "Deplacer le polygone",
  "imgmap.ERR_EXCANVAS_LOAD" : "Erreur de chargement Excanvas. Essayez de rafraichir la page",
  "imgmap.ERR_INVALID_COORDS" : "Coordonnees invalides"	
});
